### ISSUE TITLE
获取基金净值估算（实时）  接口挂了

### ISSUE THREAD

**Issue by idsbllp** [kouchao/TiantianFundApi#10]
![image](https://github.com/kouchao/TiantianFundApi/assets/16137670/d39c3a8a-2a1a-4da0-8540-350d772874ba)

**Comment by kouchao** [comment]
<img width="620" alt="image" src="https://github.com/kouchao/TiantianFundApi/assets/23720738/cc75a045-8940-4640-aaca-2715c811d118">

官方限制非指数类暂停基金净值估算展示。
