### ISSUE TITLE
测试用例全部404

### ISSUE THREAD

**Issue by superHamsa** [kouchao/TiantianFundApi#11]
![image](https://github.com/kouchao/TiantianFundApi/assets/22582986/aa549cb0-f293-4686-b1f4-46e0051d7243)

这个项目现在还能用吗

**Comment by kouchao** [comment]
在本地测试了一下，有 2 个已知的接口存在问题，其他的都是可以用的。

**Comment by superHamsa** [comment]
![image](https://github.com/kouchao/TiantianFundApi/assets/22582986/2f2a330a-33c1-47a0-8158-041eddac647b)

我的电脑上文件路径格式不对，和node版本有关系吗，我是18.18.2

**Comment by kouchao** [comment]
没有处理windows的路径，晚些时间改一下

**Comment by kouchao** [comment]
已修复
