### ISSUE TITLE
获取大盘指数

### ISSUE THREAD

**Issue by nidegexing** [kouchao/TiantianFundApi#3]
你好，感谢你的开源奉献。
看了下文档说明，没找到获取大盘指数价格的api，比如上证指数 000001 ，请问可以获取到么

**Comment by kouchao** [comment]
现在可以使用[股票相关接口](https://kouchao.github.io/TiantianFundApi/apis/#股票)查询，vercel上预览上证指数详情（见文档[股票-股票详情](https://kouchao.github.io/TiantianFundApi/apis/#股票详情)）：[https://tiantian-fund-api.vercel.app/api/action?action_name=stockGet&code=000001](https://tiantian-fund-api.vercel.app/api/action?action_name=stockGet&code=000001)

**Comment by yyh1413** [comment]
哥 这个接口挺牛的   有效期多久呀 ，会不会调几天，token过期就没了，还是你打算收费吗，小白党想问问。。。。

**Comment by yyh1413** [comment]
我查000001为什么是太平银行？

**Comment by kouchao** [comment]
新增一个 `type` 类型（暂定）用于区分市场
- 其他：`0`
- 上证：`1`
- 未知: `2`
- 港股：`116`
- 美股：`105`
- 英股：`155`

使用 [type=1&code=000001](https://tiantian-fund-api.vercel.app/api/action?action_name=stockGet&type=1&code=000001)获取上证指数详情
