### ISSUE TITLE
请问下 /fundSearch这个搜索基金接口

### ISSUE THREAD

**Issue by yyh1413** [kouchao/TiantianFundApi#5]
这个接口没有分页吗 为什么每次都搜出来最多10条，比如【华夏】【易方达】，他肯定不止10条
即使加上分页参数也不好用那。。。

**Comment by kouchao** [comment]
现在可以使用[基金搜索-以名称接口](https://kouchao.github.io/TiantianFundApi/apis/#%E5%9F%BA%E9%87%91%E6%90%9C%E7%B4%A2-%E4%BB%A5%E5%90%8D%E7%A7%B0)分页查询
