### ISSUE TITLE
获取基金累计收益的INDEXYIELD参数不生效

### ISSUE THREAD

**Issue by SunRunAwayAwayAway** [kouchao/TiantianFundApi#7]
curl "https://tiantian-fund-api.vercel.app/api/action?action_name=fundVPageAcc&FCODE=005062&INDEXYIELD=000300"

{"data":[{"PDATE":"2023-06-09","YIELD":"0.00","INDEXYIELD":"0.00","FUNDTYPEYIELD":"0.00","BENCHQUOTE":"0.00"},{"PDATE":"2023-06-12","YIELD":"0.80","INDEXYIELD":"0.30","FUNDTYPEYIELD":"0.22","BENCHQUOTE":"0.29"},{"PDATE":"2023-06-13","YIELD":"1.13","INDEXYIELD":"0.57","FUNDTYPEYIELD":"0.78","BENCHQUOTE":"0.54"},{"PDATE":"2023-06-14","YIELD":"1.28","INDEXYIELD":"0.57","FUNDTYPEYIELD":"0.78","BENCHQUOTE":"0.55"},{"PDATE":"2023-06-15","YIELD":"2.21","INDEXYIELD":"1.45","FUNDTYPEYIELD":"2.28","BENCHQUOTE":"1.38"},{"PDATE":"2023-06-16","YIELD":"2.56","INDEXYIELD":"2.30","FUNDTYPEYIELD":"3.26","BENCHQUOTE":"2.19"},{"PDATE":"2023-06-19","YIELD":"2.27","INDEXYIELD":"2.03","FUNDTYPEYIELD":"2.88","BENCHQUOTE":"1.93"},{"PDATE":"2023-06-20","YIELD":"2.03","INDEXYIELD":"1.94","FUNDTYPEYIELD":"2.78","BENCHQUOTE":"1.84"},{"PDATE":"2023-06-21","YIELD":"0.55","INDEXYIELD":"-0.31","FUNDTYPEYIELD":"0.95","BENCHQUOTE":"-0.29"},{"PDATE":"2023-06-26","YIELD":"-0.86","INDEXYIELD":"-2.04","FUNDTYPEYIELD":"-0.45","BENCHQUOTE":"-1.94"},{"PDATE":"2023-06-27","YIELD":"0.25","INDEXYIELD":"-1.02","FUNDTYPEYIELD":"0.47","BENCHQUOTE":"-0.97"},{"PDATE":"2023-06-28","YIELD":"0.35","INDEXYIELD":"-1.12","FUNDTYPEYIELD":"0.32","BENCHQUOTE":"-1.06"},{"PDATE":"2023-06-29","YIELD":"0.82","INDEXYIELD":"-1.15","FUNDTYPEYIELD":"0.19","BENCHQUOTE":"-1.09"},{"PDATE":"2023-06-30","YIELD":"1.67","INDEXYIELD":"-0.18","FUNDTYPEYIELD":"1.00","BENCHQUOTE":"-0.17"},{"PDATE":"2023-07-03","YIELD":"2.29","INDEXYIELD":"0.54","FUNDTYPEYIELD":"1.83","BENCHQUOTE":"0.52"},{"PDATE":"2023-07-04","YIELD":"2.59","INDEXYIELD":"0.76","FUNDTYPEYIELD":"2.11","BENCHQUOTE":"0.73"},{"PDATE":"2023-07-05","YIELD":"2.01","INDEXYIELD":"0.19","FUNDTYPEYIELD":"1.38","BENCHQUOTE":"0.18"},{"PDATE":"2023-07-06","YIELD":"1.59","INDEXYIELD":"-0.35","FUNDTYPEYIELD":"0.74","BENCHQUOTE":"-0.33"},{"PDATE":"2023-07-07","YIELD":"1.19","INDEXYIELD":"-0.80","FUNDTYPEYIELD":"0.19","BENCHQUOTE":"-0.75"},{"PDATE":"2023-07-10","YIELD":"1.61","INDEXYIELD":"-0.42","FUNDTYPEYIELD":"0.66","BENCHQUOTE":"-0.40"},{"PDATE":"2023-07-11","YIELD":"2.33","INDEXYIELD":"0.33","FUNDTYPEYIELD":"1.33","BENCHQUOTE":"0.32"}],"errorCode":0,"firstError":null,"success":true,"hasWrongToken":null,"totalCount":21,"expansion":{"aboutAcc":[{"code":"005062","name":"博时中证500指数增强A"},{"code":"DC20004","name":"东财指数基金"},{"code":"000905","name":"中证500"}],"changeInfo":[{"STYPE":"2","BONUS":null,"ACC":null,"FSRQ":"2020-12-23"}],"syl":"2.33","MAXRETRA":null},"jf":"pj"}

**Comment by kouchao** [comment]
文档中字段 ~`INDEXYIELD`~ 错误，应该是 `INDEXCODE`。
例如：https://tiantian-fund-api.vercel.app/api/action?action_name=fundVPageAcc&FCODE=005062&INDEXCODE=000300
