### ISSUE TITLE
Axios 0.8.1 到 1.5.1 跨站请求伪造漏洞

### ISSUE THREAD

**Issue by Goodeve0** [kouchao/TiantianFundApi#8]
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
No fix available
node_modules/tiantian-fund-api/node_modules/axios
  tiantian-fund-api  *
  Depends on vulnerable versions of axios

**Comment by kouchao** [comment]
thanks
